In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Load raw data
import pandas as pd
df = pd.read_csv("../data/raw_data.csv", header=[0, 1])

print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
df.head()

Shape: (1486, 6)

Columns: [('Date', 'Unnamed: 0_level_1'), ('Close', 'RELIANCE.NS'), ('High', 'RELIANCE.NS'), ('Low', 'RELIANCE.NS'), ('Open', 'RELIANCE.NS'), ('Volume', 'RELIANCE.NS')]

,Date,Close,High,Low,Open,Volume
,Unnamed: 0_level_1,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS,RELIANCE.NS
0,2020-01-01,675.324158,683.152852,673.490062,679.081936,14004468
1,2020-01-02,686.821228,689.348791,676.397899,676.397899,17710316
2,2020-01-03,687.648804,689.661895,681.318729,685.792252,20984698
3,2020-01-06,671.700623,683.510705,670.134872,679.976657,24519177
4,2020-01-07,682.034546,686.463335,677.068889,679.529321,16683622

In [3]:
# Flatten the multi-level columns
df.columns = ['_'.join(col).strip() for col in df.columns.values]

print("Columns after fix:", df.columns.tolist())
df.head()

Columns after fix: ['Date_Unnamed: 0_level_1', 'Close_RELIANCE.NS', 'High_RELIANCE.NS', 'Low_RELIANCE.NS', 'Open_RELIANCE.NS', 'Volume_RELIANCE.NS']

,Date_Unnamed: 0_level_1,Close_RELIANCE.NS,High_RELIANCE.NS,Low_RELIANCE.NS,Open_RELIANCE.NS,Volume_RELIANCE.NS
0,2020-01-01,675.324158,683.152852,673.490062,679.081936,14004468
1,2020-01-02,686.821228,689.348791,676.397899,676.397899,17710316
2,2020-01-03,687.648804,689.661895,681.318729,685.792252,20984698
3,2020-01-06,671.700623,683.510705,670.134872,679.976657,24519177
4,2020-01-07,682.034546,686.463335,677.068889,679.529321,16683622

In [4]:
# Check actual column names
print("All flattened columns:")
for i, col in enumerate(df.columns):
    print(f"{i}: '{col}'")

All flattened columns:
0: 'Date_Unnamed: 0_level_1'
1: 'Close_RELIANCE.NS'
2: 'High_RELIANCE.NS'
3: 'Low_RELIANCE.NS'
4: 'Open_RELIANCE.NS'
5: 'Volume_RELIANCE.NS'

In [5]:
#Rename columns to simple names
df.rename(columns={
    'Date_Unnamed: 0_level_1' : 'Date',
    'Close_RELIANCE.NS'        : 'Close',
    'High_RELIANCE.NS'         : 'High',
    'Low_RELIANCE.NS'          : 'Low',
    'Open_RELIANCE.NS'         : 'Open',
    'Volume_RELIANCE.NS'       : 'Volume'
}, inplace=True)

print("Renamed columns:", df.columns.tolist())
df.head()

Renamed columns: ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']

         Date       Close        High         Low        Open    Volume
0  2020-01-01  675.324158  683.152852  673.490062  679.081936  14004468
1  2020-01-02  686.821228  689.348791  676.397899  676.397899  17710316
2  2020-01-03  687.648804  689.661895  681.318729  685.792252  20984698
3  2020-01-06  671.700623  683.510705  670.134872  679.976657  24519177
4  2020-01-07  682.034546  686.463335  677.068889  679.529321  16683622

In [6]:
df.head()

         Date       Close        High         Low        Open    Volume
0  2020-01-01  675.324158  683.152852  673.490062  679.081936  14004468
1  2020-01-02  686.821228  689.348791  676.397899  676.397899  17710316
2  2020-01-03  687.648804  689.661895  681.318729  685.792252  20984698
3  2020-01-06  671.700623  683.510705  670.134872  679.976657  24519177
4  2020-01-07  682.034546  686.463335  677.068889  679.529321  16683622

In [7]:
# Convert Date to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Sort by date (oldest to newest)
df.sort_values('Date', inplace=True)

# Reset index
df.reset_index(drop=True,inplace=True)

print("Date range:", df['Date'].min(), "to", df['Date'].max())
print("Data type of Date:", df['Date'].dtype)
df.head()

Date range: 2020-01-01 00:00:00 to 2025-12-30 00:00:00
Data type of Date: datetime64[ns]

        Date       Close        High         Low        Open    Volume
0 2020-01-01  675.324158  683.152852  673.490062  679.081936  14004468
1 2020-01-02  686.821228  689.348791  676.397899  676.397899  17710316
2 2020-01-03  687.648804  689.661895  681.318729  685.792252  20984698
3 2020-01-06  671.700623  683.510705  670.134872  679.976657  24519177
4 2020-01-07  682.034546  686.463335  677.068889  679.529321  16683622

In [8]:
print("Missing values in each column:")
print(df.isnull().sum())
print(f"\nTotal missing values: {df.isnull().sum().sum()}")

Missing values in each column:
Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

Total missing values: 0

In [9]:
# Drop rows where ALL values are missing
df.dropna(how='all', inplace=True)

# Fill any remaining missing values using forward fill
# (use previous day's value to fill gap)
df.ffill(inplace=True)

# Double check
print("Missing values after cleaning:", df.isnull().sum().sum())
print("Shape after cleaning:", df.shape)

Missing values after cleaning: 0
Shape after cleaning: (1486, 6)

In [10]:
print("Data types before fix:")
print(df.dtypes)

# Convert price columns to float
price_cols = ['Open', 'High', 'Low', 'Close']
df[price_cols] = df[price_cols].astype(float)

# Convert volume to integer
df['Volume'] = df['Volume'].astype(int)

print("\nData types after fix:")
print(df.dtypes)

Data types before fix:
Date      datetime64[ns]
Close            float64
High             float64
Low              float64
Open             float64
Volume             int64
dtype: object

Data types after fix:
Date      datetime64[ns]
Close            float64
High             float64
Low              float64
Open             float64
Volume             int64
dtype: object

In [11]:
duplicates = df.duplicated().sum()
print(f"Duplicate rows: {duplicates}")

# Remove if any
df.drop_duplicates(inplace=True)
print(f"Shape after removing duplicates: {df.shape}")

Duplicate rows: 0
Shape after removing duplicates: (1486, 6)

In [12]:
print("=" * 45)
print("CLEANED DATA SUMMARY")
print("=" * 45)
print(f"Total rows       : {len(df)}")
print(f"Total columns    : {len(df.columns)}")
print(f"Date range       : {df['Date'].min().date()} to {df['Date'].max().date()}")
print(f"Missing values   : {df.isnull().sum().sum()}")
print(f"Duplicates       : {df.duplicated().sum()}")
print("=" * 45)
df.describe()

=============================================
CLEANED DATA SUMMARY
=============================================
Total rows       : 1486
Total columns    : 6
Date range       : 2020-01-01 to 2025-12-30
Missing values   : 0
Duplicates       : 0
=============================================

,Date,Close,High,Low,Open,Volume
count,1486,1486.000000,1486.000000,1486.000000,1486.000000,1.486000e+03
mean,2022-12-29 01:34:57.981157376,1147.187895,1158.962975,1136.265099,1147.842012,1.812902e+07
min,2020-01-01 00:00:00,395.482513,424.985445,391.724735,409.864893,0.000000e+00
25%,2021-06-29 06:00:00,994.736282,1009.926259,985.453494,997.775487,9.584944e+06
50%,2022-12-26 12:00:00,1161.183594,1169.942527,1150.965004,1161.403925,1.332284e+07
75%,2024-07-02 18:00:00,1316.421875,1323.090739,1300.431217,1318.708240,2.037365e+07
max,2025-12-30 00:00:00,1589.138184,1596.980166,1573.851280,1592.662006,1.426834e+08
std,NaN,240.345686,240.314000,240.114533,240.088987,1.516583e+07

In [13]:
# Save to processed_data.csv
df.to_csv("../data/processed_data.csv", index=False)
print("✅ Cleaned data saved to data/processed_data.csv")

✅ Cleaned data saved to data/processed_data.csv